import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from '@/context/AuthContext'; // Importer AuthProvider

export default function RootLayout({ children }) {
  return (
    <html lang="fr"> {/* Changed lang to fr as per example */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {/* Envelopper avec AuthProvider */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
